version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - OPENWEATHERMAP_API_KEY=your_api_key_here  # Replace with your actual API key
      # You can add other environment variables here as needed
      # - MONGODB_URI=mongodb://mongo:27017/air_quality_db
    # If using MongoDB, uncomment this
    # depends_on:
    #   - mongo

  # If using MongoDB, uncomment this
  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db

# If using MongoDB, uncomment this
# volumes:
#   mongo-data: 